name: PHP Lints

on:
  push:
  pull_request:
  schedule:
    - cron: '55 3 * * SUN'

permissions: {}

jobs:
  run:
    runs-on: ubuntu-latest
    name: "PHP Lints"
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.3

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Validate composer.json
        run: composer validate

      - name: Lint with php-cs-fixer
        run: vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

      - name: Lint with phpcs
        run: vendor/bin/phpcs --standard=PSR2 src/

      - name: Lint with phpstan
        run: vendor/bin/phpstan analyze
